version: '3'

services:
  php:
    container_name: php
    build: ./docker/php
    volumes:
    - .:/var/www
    environment:
      TZ: Asia/Tokyo
    restart: always

  nginx:
    container_name: nginx
    build: ./docker/nginx
    ports:
    - 80:80
    - 443:443
    volumes:
    - .:/var/www
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php
    restart: always
    
